---
title: "About"
---

## Introduction

Hi, my name is Mfundo Monchwe and I'm a data scientist, reseacher, and freelancer. I have a passion for using data to solve complex problems and help orgnanizations make data-driven decision.

## Education
I have a Bachelor's degreee and Honors degree in Data Sciences from Sol Plaatje University. I have a background in Statistics, Mathematics, and Machine Learning.

- Currently doing my Masters in Stastistics at the University of KwaZulu-Natal.

## Work Experience

### Notto Africa
**Data Scientist--Consultant**
Johannesburg, SA
Apr 2025 – Current

* Developed a data pipeline for the Notto Africa platform, which involved data extraction, transformation, and loading (ETL) processes.

* Developed a machine learning model to predict credit scores for users based on their financial history and behavior.

* Developed an API to integrate the machine learning model with the Notto Africa platform, allowing for real-time credit score predictions.

* Collaborated with the Notto Africa team to ensure the successful deployment and integration of the data pipeline and machine learning model into the platform.

* Used KeyCloak for authentication and authorization of users on the Notto Africa platform.

* Developed Streamlit dashboards to visualize the data and provide insights into user behavior and credit scores.

### Arena Holdings
**Data Scientist**  
Johannesburg, SA
Oct 2024 – Jan 2025

•	Commercial reporting

•	Predictive modelling

•	Data analysis, visualization and engineering


### Avis Budget     
**Data Scientist**
Isando, HQ, Kempton Park, SA
Apr 2024 – Current 

• Developed shiny dashboard for ilease product 

• Performed Analysis both on Data Quality and Documentation 

• Calculated IRR and Deviations for 6 countries 

• Developed credit risk recommendation system 

• Predicting future prices of a new vehicle using ML model 

### Auditor General of South Africa
**Trainee Data Analyst**  
Pretoria East Head Office, SA  
Mar 2024 – April 2024

- Provided data analytics support to various audit business units within the organization.

- Developed data analytics models.

- Worked closely with audit business units to identify the “Value-Add”.

- Supported the line manager in providing holistic, comprehensive data analytics reports.

### Tutor
**Big Data Fundamentals and Introduction to Python Programming**  
2021
- Taught content such as data wrangling, visualization, dealing with big data, and using Python to solve problems.

### Freelance Data Scientist and Researcher
- Provided guidance for academic master's research and project execution, including data analysis, automating reports, data visualization, data wrangling, data cleaning, data mining, data engineering, machine learning, and statistics.

### Project Collaboration
**Protein Synthesis Analysis**  
Contract for 3 months

- Analyzed protein synthesis in cells and performed statistical analysis on the data.

- Worked remotely on a project based in the USA using R and Python programming languages.



## Skills

::: panel-tabset

## Programming Languages
- Python
- R
- SQL

## Data Skills
- Data Wrangling
- Data Analysis
- Data Cleaning
- Data Mining
- Data Engineering
- Data Science

## Soft Skills
- Communication
- Teamwork
- Leadership
- Time Management
- Project Management
- Critical Thinking
- Problem Solving

## Techniques
- Machine Learning
- Data Visualization

## Statistics
- Statistical methods
- Bayesian Methods
- Regression Analysis

## Tools
- Django
- Linux
- Git
- GitHub
- Microsoft Office
- Tableau
- Power BI
- KeyCloak
:::

## Contact Me

If you would like to get in touch with me,  feel free to send me an email at [diditmfundo@gmail.com](mailto:diditmfundo@gmail.com) or connect with me on [LinkedIn](https://www.linkedin.com/in/mfundo-monchwe-48883314a/). 
