---
title: "Papers"
---


## Showcasing White-Box Implementation of the RSA Digital Signature Scheme
<div class="container" style="background-color: #f8d7da; padding: 10px;">
  <p>Data security is a critical aspect of online transactions. It involves ensuring data confidentiality, data integrity, and data authenticity. While much has been done to improve data confidentiality, algorithms to address data integrity and data authenticity are rare. The RSA digital signature scheme is often used to address these issues, but it can be difficult to understand for non-experts. In this study, we showcase the implementation of a white-box RSA digital signature scheme, which is an algorithm used to ensure data confidentiality, integrity, and authenticity after online transactions. We build the proposed implementation based on the understanding that the RSA digital signature scheme is an asymmetric model that uses two keys. One key is used to sign data, and the other key is used to verify the signature. We evaluate the effectiveness of the white-box RSA digital signature scheme using a quantitative research approach, where we assess the execution time and signature verification accuracy for different values of p, q, and data lengths. We observe a tradeoff between security and execution time, and we recommend using large values of p and q for better data security.</p>
  <p>Reference: Colin Chibaya, Mfundo Monchwe, Taryn Nicole Michael, Eli Bila Nimy. Showcasing White-Box Implementation of the RSA Digital Signature Scheme, American Journal of Computer Science and Technology. Volume 5, Issue 4, December 2022, pp. 198-203.</p>
</div>


## Bayesian Convolutional Neural Networks for Coronavirus Lung Image Classification with Uncertainty Estimation
<div class="container" style="background-color: #d4edda; padding: 10px;">
  <p>Previous attempts to identify or predict coronavirus using lung imaging data have not incorporated a way to quantify the uncertainty in their predictions. Additionally, these models need more certainty quantification to raise questions about their reliability. In this chapter, we address these issues by modeling a coronavirus classification model that utilizes a Bayesian convolutional neural networks (BCNNs) approach. This probabilistic machine learning approach allows for the estimation of uncertainty, providing insight into the reliability of coronavirus image classification. We test the accuracy of the model using a comprehensive radiographical lung image dataset, revealing its capability to deliver significant uncertainty information. Furthermore, we conduct comparisons with standard CNN models, highlighting the improved performance of the BCNN model in identifying complex cases that require further inspections.</p>
  <p>Reference: Mfundo Monchwe, Ibidun C. Obagbuwa, Alfred Mwanza. Coronavirus Lung Image Classification With Uncertainty Estimation Using Bayesian Convolutional Neural Networks In: Hammouch, Z., Lahby, M., Baleanu, D. (eds) Mathematical Modeling and Intelligent Control for Combating Pandemics. Springer Optimization and Its Applications, vol 203. Springer, Cham. https://doi.org/10.1007/978-3-031-33183-1_8</p>
</div>