name: Quarto Publish to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # (OPTIONAL) Set up Python/R dependencies if needed by your Quarto project
      # For example, if you use Python:
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      #   # Then pip install dependencies, etc.

      - name: Render Quarto Project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
