name: Build Quarto Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v4
      with:
        version: stable

    - name: Install Pandoc (if needed)
      run: sudo apt-get install pandoc

    - name: Install dependencies (if using R or Python)
      run: |
        pip install -r requirements.txt || true
        Rscript -e 'if (!require("quarto")) install.packages("quarto", repos="https://cloud.r-project.org")' || true

    - name: Render Quarto site
      run: quarto render

    - name: Upload site artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site/
